### ISSUE TITLE
Missing lots of libraries

### ISSUE THREAD

**Issue by sej7278** [sandeepmistry/esp8266-Arduino#3]
https://github.com/esp8266/Arduino/tree/esp8266/libraries

vs.

https://github.com/sandeepmistry/esp8266-Arduino/tree/master/esp8266com/esp8266/libraries

**Comment by sej7278** [comment]
well the only esp8266-specific one that's missing is OneWire

**Comment by sandeepmistry** [comment]
@sej7278 hmm, this wasn't on purpose, they must have got lost during a sync.

Should we re-open this? To at least add the OneWire lib? What about the others?

**Comment by sej7278** [comment]
the OneWire library is esp8266-specific and doesn't come with the official IDE by default, i think the rest are part of the regular IDE, so don't need to be included in your platform core.

its only a few ifdefs different to the upstream library, so works fine with AVR boards still, so worth bundling it in your core certainly.

**Comment by sandeepmistry** [comment]
Re-opening to track missing OneWire lib ...

**Comment by sandeepmistry** [comment]
Address via https://github.com/sandeepmistry/esp8266-Arduino/commit/d669e77342cd69d03363e8160ce7329b52701a46
