### ISSUE TITLE
program space abstraction (PgmSpace.h) does not support strn*_P

### ISSUE THREAD

**Issue by Makuna** [sandeepmistry/esp8266-Arduino#6]
avr/pgmspace.h supports strncmp_P but the esp8266 doesn't.
The whole selection of strn*_p isn't supported.

I added this snippit  below the other versions to correct the issue.

#define strncpy_P(dest, src, size) 		strncpy((dest), (src), (size))
#define strncat_P(dest, src, size) 		strncat((dest), (src), (size))
#define strncmp_P(a, b, size) 			strncmp((a), (b), (size))
#define strnlen_P(s, size) 				strnlen((const char *)(s), (size))

**Comment by Makuna** [comment]
I added this snippit below to expose a few missed methods

#define strcasecmp_P(a, b)          strcasecmp((a), (b))

#define strncpy_P(dest, src, size) 		strncpy((dest), (src), (size))
#define strncat_P(dest, src, size) 		strncat((dest), (src), (size))
#define strncmp_P(a, b, size) 			strncmp((a), (b), (size))
#define strnlen_P(s, size) 				strnlen((const char *)(s), (size))
#define strncasecmp_P(a, b, size)       strcasecmp((a), (b), (size))

**Comment by sandeepmistry** [comment]
@Makuna thanks for bringing this up, it's probably best to bring this up upstream (https://github.com/esp8266/Arduino) by either raising an issue or submitting a pull request.

I'd like to keep this fork in sync with the ESP8266 Arduino IDE, so if it gets addressed there, the changes can be pulled in here.

Thoughts?

**Comment by Makuna** [comment]
I will get this done today and then close this.

**Comment by Makuna** [comment]
https://github.com/esp8266/Arduino/pull/107

**Comment by sandeepmistry** [comment]
@Makuna the fix for this has been merged in: https://github.com/sandeepmistry/esp8266-Arduino/commit/6a37b4461caa8bbff1ba473ec55f248cb5db3522
