### ISSUE TITLE
ESP8266WiFiClass::begin returns int but in reality its used as a wl_status_t

### ISSUE THREAD

**Issue by Makuna** [sandeepmistry/esp8266-Arduino#7]
ESP8266WiFiClass::status returns a uint8_t, but also should be a wl_status_t.

The reason this is a concern is that I am getting compile errors when I used the correct type or reuse a result variable between several of this calls.  Having it consistent would be a good thing.

**Comment by sandeepmistry** [comment]
Once again, please raise an issue or submit a pull request upstream (https://github.com/esp8266/Arduino).

**Comment by Makuna** [comment]
I will get this done today and then close this.

**Comment by Makuna** [comment]
https://github.com/esp8266/Arduino/issues/109
