### ISSUE TITLE
#include <string.h> doesn't allow access to c string functions

### ISSUE THREAD

**Issue by Makuna** [sandeepmistry/esp8266-Arduino#8]
strlen is not accessible after including string.h.

**Comment by luc-github** [comment]
I use 0.0.4 and strlen is working - I use #include <Arduino.h> but not string.h

**Comment by Makuna** [comment]
To be specific, #include <Arduino.h> from the ino or a sketch header file works.  
From a library, #include <Arduino.h> does not work.  

I have a library that in the header it has a inline function that calls it and it won't compile.

**Comment by Makuna** [comment]
It seems that strnlen is missing in some of the lower level code.

in libc_replacements.c, strlen is present but not strnlen
ets_strnlen is missing which means the rom doesn't support it.

**Comment by Makuna** [comment]
I added the following to libc_replacements.c but this file doesn't seem to get compiled with the project.

size_t strnlen(const char *s, size_t len) {
    const char *cp; 
    for (cp = s; len != 0 && *cp != '\0'; cp++, len--); 
    return (size_t)(cp - s); 
}

**Comment by sandeepmistry** [comment]
Once again, please raise an issue or submit a pull request upstream (https://github.com/esp8266/Arduino).

**Comment by Makuna** [comment]
I will get this done today and then close this.

**Comment by Makuna** [comment]
https://github.com/esp8266/Arduino/pull/108

**Comment by sandeepmistry** [comment]
@Makuna the fix for this has been merged in: https://github.com/sandeepmistry/esp8266-Arduino/commit/eab9e873a6b6cc8ea589b1f1e6f15f65ec977697
