### ISSUE TITLE
std itoa is not found with arduino.h nor stdlib.h

### ISSUE THREAD

**Issue by Makuna** [sandeepmistry/esp8266-Arduino#9]
including either of them doesn't work.
including stdlib_noniso.h does.

this makes it hard to write a simple library that can compile for AVR and ESP8266.

**Comment by sandeepmistry** [comment]
Once again, please raise an issue or submit a pull request upstream (https://github.com/esp8266/Arduino).

**Comment by Makuna** [comment]
I will get this done today and then close this.

**Comment by Makuna** [comment]
https://github.com/esp8266/Arduino/issues/110

**Comment by sandeepmistry** [comment]
@Makuna the fix for this is in master now: https://github.com/sandeepmistry/esp8266-Arduino/commit/6a7d94a2df6b89a7df9bf2c4cc792d34e94bdb25

**Comment by Makuna** [comment]
I wish I could figure how to get the bits in place.  There are no instructions for building it and what I see it wants to replace Arduino 1.6.1 and I have other projects that require 1.6.3.

**Comment by sandeepmistry** [comment]
@Makuna see: https://github.com/esp8266/Arduino/blob/esp8266/build/howto.txt

On OS X, I've renamed their ```Arduino.app``` to ```Arduino-ESP8266.app``` and have both running side by side. Not sure if the same can be done on windows.

I've enabled gitter, so let's follow up the discussion there: https://gitter.im/sandeepmistry/esp8266-Arduino

**Comment by Makuna** [comment]
One piece doesn't help...

•git - used for version control 
•make, gcc-mingw, and g++ - used to build arduino.exe (this will also pull in gcc-core) 
•perl - use this version, activestate or other distros have trouble 
•unzip, zip - for dealing with archives 
When looking at the list, only perl showed up as a package.  I searched for others and got results that didn't make sense.  I am not a unix user and I suspect there is something being assumed here.

**Comment by Makuna** [comment]
C:\GitHub\Arduino\build\build.xml:723: Execute failed: java.io.IOException: Cannot run program "unzip": CreateProcess er
ror=2, The system cannot find the file specified

**Comment by Makuna** [comment]
It seems that Cygwin didn't add its bin to the path, so the build couldn't find unzip.  Adding C:\cygwin64\bin to the path fixed the problem above.

**Comment by Makuna** [comment]
while the fixes seem to compile, I can't seem to get anything out of the uploaded code.
